export const FETCH_LIST = 'FETCH_LIST';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const SELECTED_FILE = 'SELECTED_FILE';
export const SIGN_IN = 'SIGN_IN';
export const SHOW_LOADING = 'SHOW_LOADING';
export const DOWNLOADING_FILE = 'DOWNLOADING_FILE';
export const UPLOADING_FILE = 'UPLOADING_FILE';
export const CURRENT_JACKPOT_NUMBER = 'CURRENT_JACKPOT_NUMBER';